const state={gold:500,hp:100,mana:100,level:1,xp:0,attack:28,wave:1,waveRunning:true,abilityLevel:1,items:[]};
const $=id=>document.getElementById(id);const units=$('units');const feed=$('feed');
function log(text){const el=document.createElement('div');el.innerHTML=text;feed.prepend(el)}
function render(){ $('gold').textContent=`${state.gold} G`;$('level').textContent=state.level;$('xp').textContent=`${state.xp}%`;$('attack').textContent=state.attack;$('wave').textContent=state.wave;$('hpBar').style.width=`${state.hp}%`;$('manaBar').style.width=`${state.mana}%`;}
function float(text,x=50,y=50){const e=document.createElement('div');e.className='float';e.textContent=text;e.style.left=x+'%';e.style.top=y+'%';$('combatText').append(e);setTimeout(()=>e.remove(),1000)}
function spawnWave(){units.innerHTML='';state.waveRunning=true;$('waveState').textContent='IN PROGRESS';$('nextWave').disabled=true;$('objective').textContent='Survive the enemy push.';for(let i=0;i<3+state.wave;i++){const e=document.createElement('div');e.className='enemy';e.textContent='◆';e.style.left=(68+Math.random()*18)+'%';e.style.top=(20+Math.random()*60)+'%';e.dataset.hp=35+state.wave*10;units.append(e);setTimeout(()=>enemyAttack(e),800+i*900)}log(`<b>Wave ${state.wave}</b> entered the Rift.`)}
function enemyAttack(e){if(!e.isConnected||!state.waveRunning)return;const damage=Math.max(3,8+state.wave*2-state.abilityLevel);state.hp=Math.max(0,state.hp-damage);float(`-${damage}`,48,48);render();if(state.hp<=0){state.waveRunning=false;$('waveState').textContent='DEFEATED';$('objective').textContent='The Rift has fallen. Start a new match.';$('nextWave').disabled=true;log('<b>Defeat.</b> The enemy broke through.');return}e.style.left=(45+Math.random()*10)+'%';e.style.top=(38+Math.random()*25)+'%';setTimeout(()=>enemyAttack(e),2400)}
function cast(key){if(!state.waveRunning)return;const costs={q:18,w:30,e:22,r:60};if(state.mana<costs[key]){log('<b>Not enough mana.</b>');return}state.mana-=costs[key];let damage={q:35,w:50,e:20,r:100}[key]+state.abilityLevel*8;if(key==='e'){state.hp=Math.min(100,state.hp+20);log('<b>Phase Step</b> restored 20 HP.')}else{const target=[...document.querySelectorAll('.enemy')].find(x=>x.isConnected);if(target){target.dataset.hp-=damage;float(`-${damage}`,55,42);if(+target.dataset.hp<=0){target.remove();state.gold+=45;state.xp+=20;log(`<b>${key.toUpperCase()} hit.</b> Enemy defeated. +45 G`);if(state.xp>=100){state.xp-=100;state.level++;state.attack+=6;log(`<b>Level ${state.level}!</b> Your power increased.`)}}else log(`<b>${key.toUpperCase()} cast.</b> ${damage} damage.`)}}if(key==='r')log('<b>STARFALL.</b> A massive burst hits the frontline.');render();checkWave()}
function checkWave(){if(state.waveRunning&&document.querySelectorAll('.enemy').length===0){state.waveRunning=false;$('waveState').textContent='CLEARED';$('objective').textContent='Wave cleared. Prepare for the next assault.';$('nextWave').disabled=false;state.gold+=100;log(`<b>Wave ${state.wave} cleared!</b> +100 G`);render()}}
$('nextWave').onclick=()=>{state.wave++;spawnWave();render()};$('restart').onclick=()=>{Object.assign(state,{gold:500,hp:100,mana:100,level:1,xp:0,attack:28,wave:1,abilityLevel:1,items:[]});log('<b>New match.</b> Welcome to the Rift.');spawnWave();render()};$('upgrade').onclick=()=>{if(state.gold<100)return log('<b>Need 100 G</b> for an ability upgrade.');state.gold-=100;state.abilityLevel++;state.attack+=4;log(`<b>Ability upgraded.</b> Power level ${state.abilityLevel}.`);render()};document.querySelectorAll('.ability').forEach(b=>b.onclick=()=>cast(b.dataset.ability));document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if('qwer'.includes(k))cast(k)});document.querySelectorAll('.item').forEach(item=>item.onclick=()=>{const cost=+item.dataset.cost;if(state.gold<cost)return log('<b>Not enough gold.</b>');state.gold-=cost;state.items.push(item.querySelector('b').textContent);if(item.querySelector('b').textContent==='Riftblade')state.attack+=12;if(item.querySelector('b').textContent==='Void Core')state.mana=Math.min(100,state.mana+20);log(`<b>Purchased ${item.querySelector('b').textContent}.</b>`);render()});log('<b>Welcome, Astra.</b> Hold the lanes and destroy the enemy nexus.');spawnWave();render();setInterval(()=>{if(state.waveRunning)state.mana=Math.min(100,state.mana+4),render()},1500);
