const state={gold:500,hp:100,mana:100,maxMana:100,level:1,xp:0,attack:28,wave:1,waveRunning:true,abilityLevel:1,items:[],kills:0,position:{x:50,y:50},cooldowns:{q:0,w:0,e:0,r:0},towers:{blue:[100,100],red:[100,100]},minions:[],jungle:{wolf:true,golem:true},objective:null};
const $=id=>document.getElementById(id);const units=$('units');const feed=$('feed');
const abilities={q:{cost:18,damage:35,cd:3,name:'Arc Bolt'},w:{cost:30,damage:50,cd:7,name:'Gravity Well'},e:{cost:22,damage:20,cd:6,name:'Phase Step'},r:{cost:60,damage:100,cd:25,name:'Starfall'}};
function log(text){const el=document.createElement('div');el.innerHTML=text;feed.prepend(el);while(feed.children.length>40)feed.lastChild.remove()}
function render(){ $('gold').textContent=`${state.gold} G`;$('level').textContent=state.level;$('xp').textContent=`${state.xp}%`;$('attack').textContent=state.attack;$('wave').textContent=state.wave;$('hpBar').style.width=`${Math.max(0,state.hp)}%`;$('manaBar').style.width=`${Math.min(100,state.mana/state.maxMana*100)}%`;if($('kills'))$('kills').textContent=state.kills;if($('blueTower'))$('blueTower').textContent=Math.round(state.towers.blue[0])+'%';if($('redTower'))$('redTower').textContent=Math.round(state.towers.red[0])+'%';document.querySelectorAll('.ability').forEach(b=>{const k=b.dataset.ability;const cd=state.cooldowns[k]||0;b.classList.toggle('on-cooldown',cd>0);const badge=b.querySelector('.cooldown');if(badge)badge.textContent=cd>0?cd.toFixed(1):''})}
function float(text,x=50,y=50){const e=document.createElement('div');e.className='float';e.textContent=text;e.style.left=x+'%';e.style.top=y+'%';$('combatText').append(e);setTimeout(()=>e.remove(),900)}
function moveHero(x,y){if(!state.waveRunning)return;state.position={x,y};$('heroUnit').style.left=x+'%';$('heroUnit').style.top=y+'%';float('MOVE',x,y-4)}
function spawnWave(){units.innerHTML='';state.waveRunning=true;$('waveState').textContent='IN PROGRESS';$('nextWave').disabled=true;$('objective').textContent='Push the lanes and destroy the enemy towers.';state.minions=[];for(let lane=0;lane<3;lane++){for(let i=0;i<3+Math.min(state.wave,3);i++){const e=document.createElement('div');e.className='minion enemy-minion';e.textContent='◆';e.dataset.hp=30+state.wave*8;e.dataset.lane=lane;e.style.left=(70+i*4)+'%';e.style.top=lane===0?(16+i*4)+'%':lane===1?(46+i*2)+'%':(78-i*4)+'%';units.append(e);state.minions.push(e)}}log(`<b>Wave ${state.wave}</b> — three lanes are active.`);setTimeout(enemyTick,900);setTimeout(playerWaveTick,1200);render()}
function enemyTick(){if(!state.waveRunning)return;const enemies=[...document.querySelectorAll('.enemy-minion')];enemies.forEach(e=>{let x=parseFloat(e.style.left);x=Math.max(31,x-1.2);e.style.left=x+'%';if(x<=34){const lane=+e.dataset.lane;state.towers.blue[lane===1?0:1]-=1.4;state.hp=Math.max(0,state.hp-.8)}});if(state.hp<=0)return defeat();render();setTimeout(enemyTick,900)}
function playerWaveTick(){if(!state.waveRunning)return;const enemies=[...document.querySelectorAll('.enemy-minion')];enemies.forEach(e=>{let x=parseFloat(e.style.left);x=Math.min(88,x+0.8);e.style.left=x+'%' });render();setTimeout(playerWaveTick,1100)}
function defeat(){state.waveRunning=false;$('waveState').textContent='DEFEATED';$('objective').textContent='The Rift has fallen. Start a new match.';$('nextWave').disabled=true;log('<b>Defeat.</b> Your defenses collapsed.');render()}
function targetEnemy(){return [...document.querySelectorAll('.enemy-minion,.enemy')].find(x=>x.isConnected)}
function cast(key){if(!state.waveRunning)return;const a=abilities[key];if(!a)return;if(state.cooldowns[key]>0)return log(`<b>${a.name}</b> is on cooldown.`);if(state.mana<a.cost)return log('<b>Not enough mana.</b>');state.mana-=a.cost;state.cooldowns[key]=a.cd;let damage=a.damage+state.abilityLevel*8;if(key==='e'){moveHero(Math.min(85,state.position.x+12),Math.max(12,state.position.y-8));state.hp=Math.min(100,state.hp+20);log('<b>Phase Step.</b> Astra blinked and restored 20 HP.')}else if(key==='r'){const targets=[...document.querySelectorAll('.enemy-minion,.enemy')];targets.forEach(t=>hitTarget(t,damage));log('<b>STARFALL.</b> Every enemy in the frontline was struck.')}else{const t=targetEnemy();if(t)hitTarget(t,damage);else log(`<b>${a.name}</b> fired, but missed.`)}render();checkWave()}
function hitTarget(t,damage){t.dataset.hp=+t.dataset.hp-damage;float(`-${damage}`,parseFloat(t.style.left)||55,parseFloat(t.style.top)||45);if(+t.dataset.hp<=0){t.remove();state.gold+=45;state.xp+=20;state.kills++;if(state.xp>=100){state.xp-=100;state.level++;state.attack+=6;state.maxMana+=10;state.mana=state.maxMana;log(`<b>Level ${state.level}!</b> New power unlocked.`)}log(`<b>Enemy defeated.</b> +45 G`);checkWave()}}
function checkWave(){if(state.waveRunning&&document.querySelectorAll('.enemy-minion,.enemy').length===0){state.waveRunning=false;$('waveState').textContent='CLEARED';$('objective').textContent='Wave cleared. Your gold income is ready.';$('nextWave').disabled=false;state.gold+=100;log(`<b>Wave ${state.wave} cleared!</b> +100 G`);render()}}
function attackTower(side){if(!state.waveRunning)return;const key=side==='red'?'red':'blue';state.towers[key][0]=Math.max(0,state.towers[key][0]-5);state.gold+=20;float('TOWER -5%',side==='red'?78:22,25);log(`<b>${side.toUpperCase()} tower damaged.</b> +20 G`);if(state.towers.red[0]<=0){state.towers.red[0]=0;state.waveRunning=false;$('waveState').textContent='VICTORY';$('objective').textContent='Enemy Nexus exposed — victory!';log('<b>VICTORY!</b> The enemy outer tower has fallen.')}render()}
function camp(name){if(!state.jungle[name])return log('<b>Camp cleared.</b> Return next match.');const reward=name==='wolf'?120:180;state.jungle[name]=false;state.gold+=reward;state.xp+=30;log(`<b>${name==='wolf'?'Wolf Pack':'Ancient Golem'} defeated.</b> +${reward} G`);float(`+${reward} G`,name==='wolf'?20:80,55);render()}
$('arena').addEventListener('click',e=>{const r=$('arena').getBoundingClientRect();moveHero(((e.clientX-r.left)/r.width)*100,((e.clientY-r.top)/r.height)*100)});
$('nextWave').onclick=()=>{state.wave++;spawnWave()};$('restart').onclick=()=>{Object.assign(state,{gold:500,hp:100,mana:100,maxMana:100,level:1,xp:0,attack:28,wave:1,waveRunning:true,abilityLevel:1,items:[],kills:0,position:{x:50,y:50},cooldowns:{q:0,w:0,e:0,r:0},towers:{blue:[100,100],red:[100,100]},jungle:{wolf:true,golem:true}});feed.innerHTML='';log('<b>New match.</b> Welcome to the Rift.');spawnWave();render()};$('upgrade').onclick=()=>{if(state.gold<100)return log('<b>Need 100 G</b> for an ability upgrade.');state.gold-=100;state.abilityLevel++;state.attack+=4;log(`<b>Ability upgraded.</b> Power level ${state.abilityLevel}.`);render()};document.querySelectorAll('.ability').forEach(b=>b.onclick=e=>{e.stopPropagation();cast(b.dataset.ability)});document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if('qwer'.includes(k))cast(k)});document.querySelectorAll('.item').forEach(item=>item.onclick=()=>{const cost=+item.dataset.cost;if(state.gold<cost)return log('<b>Not enough gold.</b>');state.gold-=cost;const name=item.querySelector('b').textContent;state.items.push(name);if(name==='Riftblade')state.attack+=12;if(name==='Void Core'){state.maxMana+=20;state.mana=state.maxMana}if(name==='Swift Boots')state.moveSpeed=(state.moveSpeed||1)+.15;log(`<b>Purchased ${name}.</b>`);render()});document.querySelectorAll('[data-camp]').forEach(b=>b.onclick=()=>camp(b.dataset.camp));document.querySelectorAll('[data-tower]').forEach(b=>b.onclick=()=>attackTower(b.dataset.tower));setInterval(()=>{Object.keys(state.cooldowns).forEach(k=>state.cooldowns[k]=Math.max(0,state.cooldowns[k]-.2));if(state.waveRunning)state.mana=Math.min(state.maxMana,state.mana+1.5);render()},200);log('<b>Welcome, Astra.</b> Click the battlefield to move. Use Q/W/E/R, clear waves, take camps and pressure towers.');spawnWave();render();